### ISSUE TITLE
El filtro por año no incluye 2014 y 2015

### ISSUE THREAD

**Issue by martinszy** [lanacioncom/ddjj_front_rails_lanacion#1]
Hola, creo que el filtro por años debería permitir filtrar declaraciones juradas de los últimos años.
https://github.com/lanacioncom/ddjj_front_rails_lanacion/blob/master/app/views/home/_filtros.html.erb

Actualmente parece estar hardcodeado el listado de años, idealmente debería ser dinámico, quizás basado en la fecha actual (con el riesgo de que no haya datos aun para el año actual) o basado en la ultima declaracion cargada en la db.

Como mínimo, agregar los años que faltan.

**Comment by cbertelegni** [comment]
Yes sr!
